package com.appcodecraft.linkzary.data.repository

import com.appcodecraft.linkzary.data.dao.SavedLinkDao
import com.appcodecraft.linkzary.data.entity.SavedLink
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class LinkRepository @Inject constructor(
    private val savedLinkDao: SavedLinkDao,
    private val urlMetadataExtractor: com.appcodecraft.linkzary.util.UrlMetadataExtractor
) {
    fun getAllLinks(): Flow<List<SavedLink>> = savedLinkDao.getAllLinks().flowOn(Dispatchers.IO)

    fun getLinksByCollection(collectionId: Long): Flow<List<SavedLink>> =
        savedLinkDao.getLinksByCollection(collectionId).flowOn(Dispatchers.IO)

    fun getUncategorizedLinks(): Flow<List<SavedLink>> = savedLinkDao.getUncategorizedLinks().flowOn(Dispatchers.IO)

    fun searchLinks(query: String): Flow<List<SavedLink>> = savedLinkDao.searchLinks(query).flowOn(Dispatchers.IO)

    suspend fun getLinkById(id: Long): SavedLink? = withContext(Dispatchers.IO) {
        savedLinkDao.getLinkById(id)
    }
    
    suspend fun getLinkByUrl(url: String): SavedLink? = withContext(Dispatchers.IO) {
        savedLinkDao.getLinkByUrl(url)
    }

    suspend fun insertLink(link: SavedLink): Long = withContext(Dispatchers.IO) {
        savedLinkDao.insertLink(link)
    }

    suspend fun updateLink(link: SavedLink) = withContext(Dispatchers.IO) {
        savedLinkDao.updateLink(link)
    }

    suspend fun deleteLink(link: SavedLink) = withContext(Dispatchers.IO) {
        savedLinkDao.deleteLink(link)
    }

    suspend fun deleteAllLinks() = withContext(Dispatchers.IO) {
        savedLinkDao.deleteAllLinksWithTransaction()
    }
    
    suspend fun insertLinks(links: List<SavedLink>) = withContext(Dispatchers.IO) {
        savedLinkDao.insertLinks(links)
    }
    
    suspend fun deleteLinksByIds(linkIds: List<Long>) = withContext(Dispatchers.IO) {
        savedLinkDao.deleteLinksByIds(linkIds)
    }

    suspend fun moveToCollection(linkId: Long, collectionId: Long?) = withContext(Dispatchers.IO) {
        savedLinkDao.moveToCollection(linkId, collectionId)
    }

    suspend fun updatePinStatus(linkId: Long, isPinned: Boolean) = withContext(Dispatchers.IO) {
        savedLinkDao.updatePinStatus(linkId, isPinned)
    }

    suspend fun refreshAllMetadata(onProgress: (Int, Int) -> Unit) = withContext(Dispatchers.IO) {
        val allLinks = savedLinkDao.getAllLinksSync()
        var processed = 0
        val total = allLinks.size

        allLinks.forEach { link ->
            try {
                // Fetch new metadata
                val metadata = urlMetadataExtractor.extractMetadata(link.url)

                // Update link if metadata changed or missing
                // Priority: Keep existing title if valid (unless it was autogenerated/URL), but definitely fetch image if missing
                // For "Force Refresh", we generally overwrite images/favicons, but maybe handle titles carefully.
                // Let's adopt a strategy: Update image/favicon always. Update title if current is URL-like or user forces (here we just update all).
                
                val updatedLink = link.copy(
                    // Only update title if it looks like a URL or is empty, to preserve user edits? 
                    // Or since this is "Force Refresh", maybe the user wants fresh titles too?
                    // Let's stick to updating non-user-customized fields mostly, or just everything metadata-related.
                    // Given it's "Force Refresh", updating everything derived from URL is expected.
                    // However, we should be careful about Note/Tags/Pinned/Collection.
                    
                    // We update title if it seems auto-generated or if we found a better one
                    title = if (metadata.title.isNotBlank()) metadata.title else link.title,
                    favicon = metadata.favicon ?: link.favicon,
                    previewImageUrl = metadata.previewImageUrl ?: link.previewImageUrl
                )
                
                if (updatedLink != link) {
                    savedLinkDao.updateLink(updatedLink)
                }
            } catch (e: Exception) {
                // Ignore errors for individual links
            }
            processed++
            onProgress(processed, total)
        }
    }
}